In [34]:
import torch
import torch.nn.functional as F

In [21]:
a=torch.tensor([[1,2,3],[3,4,5],[3,4,5]])

In [22]:
mask=torch.tensor([[1,1,0]])

In [24]:
a=a.masked_fill(mask, -1e9)

RuntimeError: Expected object of scalar type Byte but got scalar type Long for argument #2 'mask'

In [16]:
mask

tensor([1, 1, 1, 0, 0])

In [45]:
data = torch.randn(2, 3)

In [46]:
mask = torch.ByteTensor([[1, 0, 1], [0, 1, 0]])

In [48]:
data=data.masked_fill(mask, -1e9)

In [49]:
F.softmax(data, dim=-1)

tensor([[0.0000, 1.0000, 0.0000],
        [0.2303, 0.0000, 0.7697]])

In [51]:
import collections
a=collections.defaultdict(list)

In [53]:
a['he'].append(1)

In [54]:
a['he']

[1]

In [55]:
class TrieNode:
    # Initialize your data structure here.
    def __init__(self):
        self.children = collections.defaultdict(TrieNode)
        self.is_word = False

In [58]:
root = TrieNode()
current=root

In [63]:
word='hello world'
for letter in word:
    current = current.children[letter]
    print(current.children)

defaultdict(<class '__main__.TrieNode'>, {})
defaultdict(<class '__main__.TrieNode'>, {})
defaultdict(<class '__main__.TrieNode'>, {})
defaultdict(<class '__main__.TrieNode'>, {})
defaultdict(<class '__main__.TrieNode'>, {})
defaultdict(<class '__main__.TrieNode'>, {})
defaultdict(<class '__main__.TrieNode'>, {})
defaultdict(<class '__main__.TrieNode'>, {})
defaultdict(<class '__main__.TrieNode'>, {})
defaultdict(<class '__main__.TrieNode'>, {})
defaultdict(<class '__main__.TrieNode'>, {})


In [64]:
current=root
for letter in word:
    current = current.children.get(letter)
    if current is None:
        print(0)
print(current.is_word)

False


In [66]:
class Trie:
    def __init__(self):
        self.root = TrieNode()

    def insert(self, word):
        
        current = self.root
        for letter in word:
            current = current.children[letter]
        current.is_word = True

    def search(self, word):
        current = self.root
        for letter in word:
            current = current.children.get(letter)
            if current is None:
                return False
        return current.is_word

In [67]:
trie=Trie()

In [68]:
current=trie.root
word='hello world'
for letter in word:
    current = current.children[letter]
    print(current.children)


defaultdict(<class '__main__.TrieNode'>, {})
defaultdict(<class '__main__.TrieNode'>, {})
defaultdict(<class '__main__.TrieNode'>, {})
defaultdict(<class '__main__.TrieNode'>, {})
defaultdict(<class '__main__.TrieNode'>, {})
defaultdict(<class '__main__.TrieNode'>, {})
defaultdict(<class '__main__.TrieNode'>, {})
defaultdict(<class '__main__.TrieNode'>, {})
defaultdict(<class '__main__.TrieNode'>, {})
defaultdict(<class '__main__.TrieNode'>, {})
defaultdict(<class '__main__.TrieNode'>, {})


In [69]:
current=trie.root
for letter in word:
    current = current.children.get(letter)
    if current is None:
        print(0)
print(current.is_word)

False


In [72]:
a=torch.tensor([[2,3],[1,1]])
b=torch.tensor([[1,1],[2,3]])
torch.mm(a,b)

tensor([[ 8, 11],
        [ 3,  4]])